version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/scrapingant4j-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/scrapingant4j-spring-boot-starter"
    schedule:
      interval: "weekly"
